# eturnal STUN/TURN server configuration file.
#
# This file is written in YAML.
#
# YAML IS INDENTATION-SENSITIVE, MAKE SURE YOU INDENT CORRECTLY.

eturnal:

  ## Offer STUN and TURN on 3478 (UDP/TCP) and 5349 (TLS):
  listen:
    -
      ip: "::"
      port: 3478
      transport: udp
    -
      ip: "::"
      port: 3478
      transport: tcp
    -
      ip: "::"
      port: 5349
      transport: tls

  ## Shared secret for deriving temporary TURN credentials (MUST be specified):
  #secret: "long-and-cryptic"

  ## The server's public IPv4 address (default: address of $(hostname --fqdn)):
  #relay_ipv4_addr: "203.0.113.4"
  ## The server's public IPv6 address (optional):
  #relay_ipv6_addr: "2001:db8::4"

  ## TLS certificate/key files (must be readable by 'eturnal' user):
  #tls_crt_file: /etc/eturnal/tls/crt.pem
  #tls_key_file: /etc/eturnal/tls/key.pem

  ## UDP relay port range (usually, several ports per A/V call are required):
  relay_min_port: 49152     # This is the default.
  relay_max_port: 65535     # This is the default.

  ## Max. number of TURN permissions per connection:
  max_permissions: 10       # This is the default.

  ## Max. B/s for TCP/TLS connections:
  max_bps: unlimited        # This is the default.

  ## Reject TURN relaying from/to these addresses/networks:
  blacklist:
    - "127.0.0.0/8"         # IPv4 loopback (blacklisted by default).
    - "::1"                 # IPv6 loopback (blacklisted by default).
    - "2001::/32"           # Teredo (blacklisted by default).
    - "2002::/16"           # 6to4 (blacklisted by default).

  ## Logging configuration:
  log_level: info           # critical | error | warning | notice | info | debug
  log_rotate_size: 10485760 # 10 MiB (default: unlimited, i.e., no rotation).
  log_rotate_count: 10      # Keep 10 rotated log files.
